### ISSUE TITLE
Content and slug behaviour dependent from currently opened page when `npm run dev` starts (astro:content)

### ISSUE THREAD

**Issue by gustawdaniel** [jlarmstrongiv/astro-i18n-aut#19]
Problem:

I using this package with `astro:content`, but can't achieve stable behaviour of my blog when I working on routing to content.

I assumed convention when the first component of the path is language if it is a language different than English.

Example for static pages:

`/` - main page in English
`/pl` - main page in Polish

Example for blog posts

`/post/hello-world` - blog post in English
`/pl/post/widaj-swiecie` - blog post in Polish

I have no problem with static pages, like `index` or `about` but for content I see that some posts work or do not work depending on the page on which I have opened the browser during the `npm run dev` command.

Test

I have closed the browser. I starting my blog.

```
npm run dev 
```

I see http://localhost:3000/ in English, http://localhost:3000/pl in Polish, and http://localhost:3000/es in Spanish as I expected.
My blog post http://localhost:3000/post/hi is displayed correctly.

but when I enter http://localhost:3000/pl/post/witaj-swiecie I see 404.
To see its content I have to use http://localhost:3000/post/witaj-swiecie but then I lose info about the language in the URL and the language of the rest layout is wrongly recognized.

But it is only half of the problem...

Now I typing http://localhost:3000/pl/post/witaj-swiecie  in the browser address again to see 404.

I turned down the server in the Linux console.

Then typed 

```
npm run dev 
```

again and saw my Polish blog post on http://localhost:3000/pl/post/witaj-swiecie

But... it is not a solution because of when I entered now

http://localhost:3000/pl or http://localhost:3000/ I see it works because these are static pages, but when I want to check an English blog post and type

http://localhost:3000/post/hi

I see now 404, to see this post I can't see it even typing

http://localhost:3000/en/post/hi

because I am instantly redirected to http://localhost:3000/post/hi

In the console, I can see warnings

```
09:11:13 [getStaticPaths] A `getStaticPaths()` route pattern was matched, but no matching static path was found for the requested path `/post/hi`.

Possible dynamic routes being matched: src/pages/post/[...slug].astro.
09:11:13 [serve]    404      
```

I created the branch `astro-i18n-aut` in my blog so you can reproduce it.

https://github.com/gustawdaniel/gustawdaniel/tree/astro-i18n-aut

**Comment by jlarmstrongiv** [comment]
You are right!  

One change that is needed is updating the imports in the `astro.config.mjs` file:

```js
import { i18n, defaultLocaleSitemapFilter } from "astro-i18n-aut/integration";
```

However, I believe the `injectRoutes()` behavior has changed and broken `astro-i18n-aut` in the `dev` environment from what I’ve tested.

**Comment by jlarmstrongiv** [comment]
Follow https://github.com/withastro/astro/issues/8241 for updates

**Comment by jlarmstrongiv** [comment]
Hey @ansmlc there was an issue with handling trailing slashes that I just fixed, please try again with the latest version!  

If you have an issue with translations in `preview`, please open a new issue.  The `preview` and `dev` commands depend on different Astro internals, so only `dev` is broken.  Otherwise, it’s a fixable bug in the library.

**Comment by jlarmstrongiv** [comment]
Also @ansmlc if you have a repository or example project I could look at, please send it my way

**Comment by dallyh** [comment]
@jlarmstrongiv Please is this still an issue? I'd like to know before I get to work on a blog, I'd like to have this clarified. I'm assuming that it still happens with version 4 of astro, am I right? Also I see that you updated the status of this issue, but I have figured that I'd still ask just to be sure. Thanks!

**Comment by dallyh** [comment]
> @jlarmstrongiv Please is this still an issue? I'd like to know before I get to work on a blog, I'd like to have this clarified. I'm assuming that it still happens with version 4 of astro, am I right? Also I see that you updated the status of this issue, but I have figured that I'd still ask just to be sure. Thanks!

To save you some time, this indeed still happens. My setup was slightly different, but dev server returns erratic 404's and build/preview is fine.

**Comment by jlarmstrongiv** [comment]
@dallyh feel free to ask in the Astro discord.  I’ve done everything I can to try and get that issue prioritized.

**Comment by jlarmstrongiv** [comment]
Fixed in 0.8.0
